### ISSUE TITLE
A way to Read the active flags.

### ISSUE THREAD

**Issue by jordwalke** [the-lambda-church/merlin#375] opened 2015-03-14 09:04 UTC
Merlin offers a way to add/remove flags, but it seems the ability to read the active flags is not working (`merlin#CompleteFlags`).

I know that `merlin` is correctly reading the `FLG` portion of my `.merlin` file, but the `merlin#CompleteFlags` method only returns the "relevant flags", which don't include the ones I've listed in my `.merlin` file. Is this a bug?

**Comment by trefis** [comment] 2015-03-31 16:19
I don't thing it's a bug, I think it's "by design".
To get a list of all the active flags (and their source), you can call `:py merlin.dump("flags")` from vim and `M-x merlin-dump RET flags RET` from emacs. (only available on master though, not in the current opam package).

If you feel like this is a thing you'll use often, I can add a nicer command in vim (`MerlinFlags` or something ?). Otherwise I guess you can close this :)

**Comment by jordwalke** [comment] 2015-03-31 17:47
Dump is fine. Thanks.

**Closed** 2015-04-10 13:28 UTC
Labels: enhancement
