### ISSUE TITLE
:Locate doesn't work on files with syntax extension

### ISSUE THREAD

**Issue by ygrek** [the-lambda-church/merlin#339] opened 2014-12-23 07:44 UTC
It works before the first line of modified syntax and doesn't work after. But IIUC the `.cmt` files have the correct location, so maybe merlin should fallback to use that information directly?

**Comment by trefis** [comment] 2015-03-11 14:06
Hi, sorry for the (very) late answer.

Here are some remarks/questions : 
- if the problem is related to syntax "errors" then locate won't be the only piece that doesn't work. nothing will "work"
- are you talking about PPX extensions, we know have support for them so this might be a non-problem now.
- if not, what extensions are you talking about, we might be able to support it without too much pain.
- using the cmt instead of the buffer content will in the general case result to incorrect results (since they won't be synchronized)
- that being said, it could probably be done. I have a cleaned version of locate not yet merged into master, once it is I will try to add this cmt fallback (if you still need it)

**Comment by trefis** [comment] 2015-05-07 20:45
Ping.

**Comment by ygrek** [comment] 2015-05-07 21:19
Yes, I was talking about syntax error because of camlp4 syntax extension used. In my case this was mikmatch, but afaics now it works fine with merlin 2.0 - :Locate successfully locates definitions in camlp4-processed files - is it expected?

**Comment by trefis** [comment] 2015-05-07 21:37
> :Locate successfully locates definitions in camlp4-processed files - is it expected?

I'm not sure I understand. Do you mean that locate brings you to a file which has been generated by camlp4?

If yes, then it is kind of expected yes. To identify the source file locate will use the "source digest" field found in the .cmt file. If the cmt was generated from the camlp4-generated file, then merlin should bring you in that file.

Otherwise I don't know what you meant.

**Comment by ygrek** [comment] 2015-05-07 21:47
No, I mean that I am browsing code in file with camlp4 syntax extension used - so it is not regular ocaml code - and :Locate is still able to point at the correct definition for any value (outside of the modified syntax) - this was not the case when this bug was submitted iirc - so it can be closed now.

**Comment by trefis** [comment] 2015-05-08 01:09
OK thank you!

**Closed by trefis** 2015-05-08 01:09 UTC
Labels: enhancement
